package tech.uom.lib.assertj.assertions;

import javax.measure.Unit;

/**
 * {@link Unit} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractUnitAssert} instead.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public class UnitAssert extends AbstractUnitAssert<UnitAssert, Unit> {

    /**
     * Creates a new <code>{@link UnitAssert}</code> to make assertions on actual Unit.
     *
     * @param actual the Unit we want to make assertions on.
     */
    public UnitAssert(Unit actual) {
        super(actual, UnitAssert.class);
    }

    /**
     * An entry point for UnitAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myUnit)</code> and get specific assertion with code completion.
     *
     * @param actual the Unit we want to make assertions on.
     * @return a new <code>{@link UnitAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static UnitAssert assertThat(Unit actual) {
        return new UnitAssert(actual);
    }
}
